### ISSUE TITLE
Ban history does not show

### ISSUE THREAD

**Issue by css522** [leedrum/faceit-exts#57]
Ban history no longer shows on user profiles. Tried using the extension in both firefox and chrome, same issue on both browsers

**Comment by leedrum** [comment]
@css522 thank you for the issue. A long time no play. I will fix it soon

**Comment by leedrum** [comment]
https://github.com/leedrum/faceit-exts/releases/tag/1.1.24 
It is under reviewing by `google`

**Comment by leedrum** [comment]
@css522 The extension has been published by google, please update the extension. 
I will close this issue btw.

**Comment by leedrum** [comment]
@css522 The extension has been published by google, please update the extension. 
I will close this issue btw.
